### ISSUE TITLE
Did I missed something here

### ISSUE THREAD

**Issue by 4lx4life** [karma9874/AndroRAT#100]
$ python androRAT.py --build --shell -i 192.168.49.2 -p 80 -o AcrobatVersion
Traceback (most recent call last):
  File "C:\Users\Utilisateur\AndroRat\androRAT.py", line 49, in <module>
    build(args.ip,port_,args.output,False,None,icon)
  File "C:\Users\Utilisateur\AndroRat\utils.py", line 367, in build
    version_no = re.search(pattern, java_version.stderr).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by yuuu7** [comment]
-o name.apk
