### ISSUE TITLE
Error in line 46 and 375

### ISSUE THREAD

**Issue by Nanji47** [karma9874/AndroRAT#104]
[INFO] Generating APK
Traceback (most recent call last):
  File "/root/AndroRAT/androRAT.py", line 46, in <module>
    build(ip,port,args.output,True,port_,icon)
  File "/root/AndroRAT/utils.py", line 375, in build
    while t.is_Alive(): animate("Building APK ")
AttributeError: 'Thread' object has no attribute 'is_Alive'

**Comment by karma9874** [comment]
This issue is fixed now, you can fresh clone and try again
