### ISSUE TITLE
I'm getting this SyntaxError Anyone help out please 🙂

### ISSUE THREAD

**Issue by shuence** [karma9874/AndroRAT#120]
```
`Traceback (most recent call last):
  File "androRAT.py", line 4, in <module>
    from utils import *
  File "/home/shuence/AndroRAT/utils.py", line 188
    print(stdOutput("success")+f"Succesfully Uploaded the file \033[32m{filedata[0]+'.'+filedata[1]} in /sdcard/temp/")
                                                                                                                     ^
SyntaxError: invalid syntax`
```

I'm using Ubuntu 20.04 LTS Os

**Comment by savageking867** [comment]
use python3 instead of python idiots

**Comment by shuence** [comment]
Thanks bruhh it's working now ... !

**Comment by xrude** [comment]
I am getting this error on python3

 python3 androRAT.py --build -i 192.168.0.103 -p 4444 -o try.apk
```
Traceback (most recent call last):
  File "/Users/xrude/android-attack/AndroRAT/androRAT.py", line 52, in <module>
    build(args.ip,port_,args.output,False,None,icon)
  File "/Users/xrude/android-attack/AndroRAT/utils.py", line 370, in build
    version_no = re.search(pattern, java_version.stderr).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
```
