### ISSUE TITLE
Broken pipe error someone help me out 🥲 

### ISSUE THREAD

**Issue by abekuchbhi** [karma9874/AndroRAT#128]
Traceback (most recent call last):  File "/data/data/com.termux/files/home/AndroRAT/androRAT.py", line 58, in <module>    get_shell(args.ip,args.port)  File "/data/data/com.termux/files/home/AndroRAT/utils.py", line 342, in get_shell    conn.send(message_to_send.encode("UTF-8"))BrokenPipeError: [Errno 32] Broken pipe

**Comment by sai2730** [comment]
Use python3 instead of python

**Comment by S4imD3v1L** [comment]
> Use python3 instead of python

Still not working with python3, same problem
