### ISSUE TITLE
Getting 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by xrude** [karma9874/AndroRAT#134]
Getting this error
@karma9874 
python3 androRAT.py --build -i 192.168.0.103 -p 4444 -o try.apk

```
Traceback (most recent call last):
  File "/Users/xrude/android-attack/AndroRAT/androRAT.py", line 52, in <module>
    build(args.ip,port_,args.output,False,None,icon)
  File "/Users/xrude/android-attack/AndroRAT/utils.py", line 370, in build
    version_no = re.search(pattern, java_version.stderr).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by karma9874** [comment]
You are using old version of AndroRat, please do git pull to update
