### ISSUE TITLE
 i Can't  shell and get user info

### ISSUE THREAD

**Issue by sarowarhosen03** [karma9874/AndroRAT#138]
Am seeing this error when shell 

![Screenshot_20220226-103556](https://user-images.githubusercontent.com/98280301/155829143-3a53435d-048c-4826-8234-4c7d5af55560.png)
`Traceback (most recent call last):
  File "/data/data/com.termux/files/home/AndroRAT/androRAT.py", line 62, in <module>                                     get_shell(args.ip,args.port)
  File "/data/data/com.termux/files/home/AndroRAT/utils.py", line 342, in get_shell                                      conn.send(message_to_send.encode("UTF-8"))
BrokenPipeError: [Errno 32] Broken pipe`

**Comment by kingof-killer** [comment]
i dont know bro sry but do you know hot to connect the device because i installed the apk and opened it but still waiting for connection

**Comment by Mdsarowarhossain** [comment]
![1646795853631](https://user-images.githubusercontent.com/98280301/157366255-8c798ad5-c9a3-4837-94cb-809a14d44e9f.jpg)
Am see this error
