### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by IAMDROPPE** [karma9874/AndroRAT#189]
[Dats]
Python 3.9.10
Kali Linux
Test: Android 10

Interpreter:/> help
Traceback (most recent call last):
  File "/home/droppe/Escritorio/Android/AndroRAT/androRAT.py", line 62, in <module>
    get_shell(args.ip,args.port) 
  File "/home/droppe/Escritorio/Android/AndroRAT/utils.py", line 342, in get_shell
    conn.send(message_to_send.encode("UTF-8"))
BrokenPipeError: [Errno 32] Broken pipe

**Comment by KoBruhh** [comment]
MEE TOO
for my phone it works fine but when I shut it down it disconnects and says Broken pipe

**Comment by mlemmlemquynh** [comment]
bruh u can use metasploit to create apk file rat,dont even need to use AndroRAT

**Comment by ShaggyAB** [comment]
i am getting same error
