### ISSUE TITLE
Application was built for an older version of android

### ISSUE THREAD

**Issue by U071CXA** [karma9874/AndroRAT#218]
Traceback (most recent call last):
  File "androRAT.py", line 62, in <module>
    get_shell(args.ip,args.port) 
  File "/home/root/AndroRAT/utils.py", line 342, in get_shell
    conn.send(message_to_send.encode("UTF-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by itachiman** [comment]
did you got any solutions bro
