### ISSUE TITLE
Traceback (most recent call last):                           File "/data/data/com.termux/files/home/AndroRAT/androRAT.py", line 62, in <module>     get_shell(args.ip,args.port)                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/data/data/com.termux/files/home/AndroRAT/utils.py", line 342, in get_shell     conn.send(message_to_send.encode("UTF-8"))             BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by nickfour** [karma9874/AndroRAT#239]
can't control

**Comment by nickfour** [comment]
![Screenshot_2022-11-17-21-55-32-08_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/105587657/202648449-a93aa788-d687-46ff-878f-e640e2bbd009.jpg)

**Comment by nickfour** [comment]
![Uploading Screenshot_2022-11-18-17-23-07-33_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by nickfour** [comment]
![Screenshot_2022-11-18-18-00-25-35_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/105587657/202690562-2cef360c-1ed7-4a7c-a6c7-bb57a87025be.jpg)
Line 62 get_shell

**Comment by nickfour** [comment]
![Screenshot_2022-11-18-17-56-29-35_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/105587657/202690793-cc3dc2f8-4307-4930-9166-69721e191c53.jpg)
Line 342 get_shell

**Comment by tydjjyrd** [comment]
how to fix it

**Comment by tydjjyrd** [comment]
![Screenshot_2022-12-12-10-38-59-85_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/106095472/207012341-5d0d03ed-51f7-4020-a1ab-4f8ff3604b06.jpg)

**Comment by ArtMst2000** [comment]
> ![Screenshot_2022-11-18-18-00-25-35_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/105587657/202690562-2cef360c-1ed7-4a7c-a6c7-bb57a87025be.jpg) Line 62 get_shell

can solve this problems ??????

**Comment by ArtMst2000** [comment]
> ![Screenshot_2022-12-12-10-38-59-85_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/106095472/207012341-5d0d03ed-51f7-4020-a1ab-4f8ff3604b06.jpg)

same problem as i am ? can solve this
