### ISSUE TITLE
git clone https://github.com/karma9874/AndroRAT.git cd AndroRAT pip install -r requirements.txt

### ISSUE THREAD

**Issue by NOTHUMANS00** [karma9874/AndroRAT#281]

**Comment by Lxck728** [comment]
Hello

**Comment by joepvd07** [comment]
if I run pip install -r requirements.txt it gives this response
Defaulting to user installation because normal site-packages is not writeable
Collecting pyngrok
  Using cached pyngrok-4.2.2.tar.gz (20 kB)
Requirement already satisfied: future in /home/joepvandessel/.local/lib/python2.7/site-packages (from pyngrok->-r requirements.txt (line 1)) (0.18.3)
Collecting PyYAML
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... |^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpctMPxb
       cwd: /tmp/pip-install-I_7x2_/pyyaml                                                                                                                                                                                        
  Complete output (46 lines):                                                                                                                                                                                                     
  running egg_info                                                                                                                                                                                                                
  creating lib/PyYAML.egg-info                                                                                                                                                                                                    
  writing lib/PyYAML.egg-info/PKG-INFO                                                                                                                                                                                            
  writing top-level names to lib/PyYAML.egg-info/top_level.txt                                                                                                                                                                    
  writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt                                                                                                                                                            
  writing manifest file 'lib/PyYAML.egg-info/SOURCES.txt'                                                                                                                                                                         
  Traceback (most recent call last):                                                                                                                                                                                              
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>                                                                                                                        
      main()                                                                                                                                                                                                                      
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main                                                                                                                            
      json_out['return_val'] = hook(**hook_input['kwargs'])                                                                                                                                                                       
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel                                                                                                    
      return hook(config_settings)                                                                                                                                                                                                
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel                                                                                                             
      return self._get_build_requires(config_settings, requirements=['wheel'])                                                                                                                                                    
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 127, in _get_build_requires                                                                                                                      
      self.run_setup()                                                                                                                                                                                                            
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 142, in run_setup                                                                                                                                
      exec(compile(code, __file__, 'exec'), locals())                                                                                                                                                                             
    File "setup.py", line 295, in <module>                                                                                                                                                                                        
      python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*',                                                                                                                                              
    File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 162, in setup                                                                                                                                      
      return distutils.core.setup(**attrs)                                                                                                                                                                                        
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup                                                                                                                                                               
      dist.run_commands()                                                                                                                                                                                                         
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands                                                                                                                                                        
      self.run_command(cmd)                                                                                                                                                                                                       
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command                                                                                                                                                         
      cmd_obj.run()                                                                                                                                                                                                               
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 296, in run                                                                                                                                
      self.find_sources()                                                                                                                                                                                                         
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 303, in find_sources                                                                                                                       
      mm.run()                                                                                                                                                                                                                    
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 534, in run                                                                                                                                
      self.add_defaults()                                                                                                                                                                                                         
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 570, in add_defaults                                                                                                                       
      sdist.add_defaults(self)                                                                                                                                                                                                    
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/py36compat.py", line 36, in add_defaults                                                                                                                      
      self._add_defaults_ext()                                                                                                                                                                                                    
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/py36compat.py", line 120, in _add_defaults_ext                                                                                                                
      self.filelist.extend(build_ext.get_source_files())                                                                                                                                                                          
    File "setup.py", line 201, in get_source_files                                                                                                                                                                                
      self.cython_sources(ext.sources, ext)                                                                                                                                                                                       
    File "/usr/lib/python2.7/distutils/cmd.py", line 105, in __getattr__                                                                                                                                                          
      raise AttributeError, attr                                                                                                                                                                                                  
  AttributeError: cython_sources                                                                                                                                                                                                  
  ----------------------------------------                                                                                                                                                                                        
ERROR: Command errored out with exit status 1: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpctMPxb Check the logs for full command output.
This is an VM of Kali Linux on an MacBook Air with the apple chip M2
