### ISSUE TITLE
signing failed 

### ISSUE THREAD

**Issue by grim123rapper** [karma9874/AndroRAT#31]
Signing the apk
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
        at s.Sign.addDigestsToManifest(Sign.java:108)
        at s.Sign.sign(Sign.java:454)
        at s.Sign.main(Sign.java:532)
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 3 more

Signing Failed

**Comment by v4yne1** [comment]
You have to use Java 8.

https://rtfm.co.ua/en/arch-linux-set-a-java-version/
