### ISSUE TITLE
shell error

### ISSUE THREAD

**Issue by geedichtnohne** [karma9874/AndroRAT#342]
Traceback (most recent call last):
  File "C:\Users\nicol\AndroRAT\androRAT.py", line 62, in <module>
    get_shell(args.ip,args.port)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicol\AndroRAT\utils.py", line 320, in get_shell
    msg = conn.recv(4024).decode("UTF-8")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 20: invalid start byte

**Comment by syedikhlas0** [comment]
hey i have same issue
