### ISSUE TITLE
when i try to build apk with ngrok I got this error

### ISSUE THREAD

**Issue by plemyashkin01** [karma9874/AndroRAT#357]
C:\Users\user\AndroRAT>python androRAT.py --build --ngrok -p 8888
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyngrok\ngrok.py", line 518, in api_request
    response = urlopen(request, encoded_data, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AndroRAT\androRAT.py", line 48, in <module>
    tcp_tunnel = ngrok.connect(port, "tcp")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyngrok\ngrok.py", line 320, in connect
    tunnel = NgrokTunnel(api_request(f"{api_url}/api/tunnels", method="POST", data=options,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyngrok\ngrok.py", line 539, in api_request
    raise PyngrokNgrokHTTPError(f"ngrok client exception, API returned {status_code}: {response_data}",
pyngrok.exception.PyngrokNgrokHTTPError: ngrok client exception, API returned 502: {"error_code":103,"status_code":502,"msg":"failed to start tunnel","details":{"err":"failed to start tunnel: You must add a credit or debit card before you can use TCP endpoints on a free account. We require a valid card as a way to combat abuse and keep the internet a safe place. This card will NOT  be charged.\nAdd a card to your account here:

**Comment by infamouskoala** [comment]
read the error lmao, it is mentioned in the last line what the error is

**Comment by HackerX0070922** [comment]
[ERROR] pyngrok not found
[INFO] Run pip3 install -r requirements.txt
Can someone help me

**Comment by PirateProxy9** [comment]
> [ERROR] pyngrok not found `[INFO]` Run pip3 install -r requirements.txt Can someone help me

u can clearly see the [INFO] telling u to install the requirements using `pip install -r requirements.txt`

**Comment by malik7568044** [comment]
Ngrok is no longer supported

**Comment by Dimmmo281** [comment]
how can I fix this problem?

**Comment by Shuaibabdi21** [comment]
Dm

**Comment by Dimmmo281** [comment]
Also, it doesn't work exactly what is related to ngrok, tell me what to do, I've tried almost everything, is it possible to integrate with something similar to it?
