### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ScriptCreater** [karma9874/AndroRAT#399]
I keep getting a error message after I connect it. Its after I type a command so not directly after but I can't  execute nothing, when I try this error message pops up and it kicks me out of lnterpreter.

The error message is:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/AndroRAT/androRAT.py", line 62, in <module>
    get_shell(args.ip,args.port)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/AndroRAT/utils.py", line 342, in get_shell
    conn.send(message_to_send.encode("UTF-8"))
BrokenPipeError: [Errno 32] Broken pipe

**Comment by NFS11** [comment]
@ScriptCreater have you modified it in any way? that happens when the code is modified
