### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by xiaaru** [karma9874/AndroRAT#53]
`c:\Users\xiaaru\AndroRAT>python androRAT.py --build -i 192.168.0.1 -p 8000 -o evil.apk
Traceback (most recent call last):
  File "androRAT.py", line 110, in <module>
    java_version = executeCMD("java -version")
  File "c:\Users\xiaaru\AndroRAT\utils.py", line 36, in executeCMD
    result = run(command, stdout=PIPE, stderr=PIPE, universal_newlines=True, shell=True)
  File "C:\Users\xiaaru\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\xiaaru\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\xiaaru\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

cannot go beyond this
:/

**Comment by karma9874** [comment]
This error is due to the missing files of python libraries I guess, maybe degrading or reinstalling python will help you

**Comment by graysuit** [comment]
@xiaaru 
Is `java.exe` on the environment path ?
This line focus-able for me:
`File "androRAT.py", line 110, in <module> java_version = executeCMD("java -version")`

This script tried to run command `java -version`, but as `java.exe` not found, it gave error file not found.
