### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe2' in file 

### ISSUE THREAD

**Issue by tonilkumar** [karma9874/AndroRAT#57]
kali@kali:~/AndroRAT$   python androRAT.py --build --ngrok [flags]
Traceback (most recent call last):
  File "androRAT.py", line 1, in <module>
    from utils import *
  File "/home/kali/AndroRAT/utils.py", line 42
SyntaxError: Non-ASCII character '\xe2' in file /home/kali/AndroRAT/utils.py on line 42, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

i got this error pls help me
![Screenshot 2021-03-13 07:59:26](https://user-images.githubusercontent.com/67651607/111322943-5c18a200-8661-11eb-8192-4f9655467e9f.png)

**Comment by karma9874** [comment]
the screenshot is not relevant to the issue,

**Comment by wiz64** [comment]
The issue may be due to outdated python version.
IT MUST BE ABOVE 3.6 ~
Try :
_python --version_
usually it may show python 2.7.X , to fix this, use python3 instead of python.
eg. ->
`python3 --version`
and for pip, use pip3 (must install it )
`sudo apt install python3-pip`
eg.
`python3 AndroRAT.py`
