### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder

### ISSUE THREAD

**Issue by Zeemongoose** [karma9874/AndroRAT#58]
root@ehsan-HP-EliteBook-8570p:/home/ehsan/Desktop/AndroRAT-master# python3 androRAT.py --build -i 192.168.0.101 -p 9898 -o text.apk
[INFO] Generating APK
[INFO] Building APK | 
[SUCCESS] Successfully apk built in /home/ehsan/Desktop/AndroRAT-master/text.apk
[INFO] Signing the apk
[INFO] Signing Apk | 
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at s.Sign.addDigestsToManifest(Sign.java:108)
	at s.Sign.sign(Sign.java:454)
	at s.Sign.main(Sign.java:532)
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more

[ERROR] Signing Failed

**Comment by karma9874** [comment]
Try using java 8
