### ISSUE TITLE
[ERROR] Signing Failed

### ISSUE THREAD

**Issue by zhangxm99** [karma9874/AndroRAT#72]
Hello , when I run the command `python androRAT.py --build -I [ip] -p 80 -o test.apk` , I got the following messages.
```
[INFO] Generating APK
[INFO] Building APK | 
[SUCCESS] Successfully apk built in /Users/zg/AndroRAT/evil.apk
[INFO] Signing the apk
[INFO] Signing Apk | 
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at s.Sign.addDigestsToManifest(Sign.java:108)
	at s.Sign.sign(Sign.java:454)
	at s.Sign.main(Sign.java:532)
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more

[ERROR] Signing Failed
```
And the size of generated file is 0
Thanks for your reply.

**Comment by zhangxm99** [comment]
This is my java version
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode)
```

**Comment by rayep** [comment]
@zhangxm99 try using Java 8. I'm using 1.8.0_292 JDK and it works.

Version output:

openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0
ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

**Comment by zhangxm99** [comment]
@rayep That worked. Thanks
