### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Poyebaneyyy** [karma9874/AndroRAT#78]
Traceback (most recent call last):
  File "C:\Users\Addddda\Desktop\AndroRAT-master\androRAT.py", line 49, in <module>
    build(args.ip,port_,args.output,False,None,icon)
  File "C:\Users\Addddda\Desktop\AndroRAT-master\utils.py", line 375, in build
    while t.isAlive(): animate("Building APK ")
AttributeError: 'Thread' object has no attribute 'isAlive'
Exception ignored in: <module 'threading' from 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\\lib\\threading.py'>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1428, in _shutdown
    lock.acquire()

**Comment by swagkarna** [comment]
@Poyebaneyyy If you are using python3.9 then u should do these changes in your code 

open utils.py  with notepad++ and navigate to line no : 375 and change from `t.isAlive()` to `t.is_alive()` and also do the same for line no 310
