### ISSUE TITLE
h

### ISSUE THREAD

**Issue by Zangetsu-code** [karma9874/AndroRAT#83]
[INFO] Generating APK
[INFO] Building APK | 
[SUCCESS] Successfully apk built in /root/Downloads/AndroRAT/MusicPlayer1.apk
[INFO] Signing the apk
[INFO] Signing Apk | 
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at s.Sign.addDigestsToManifest(Sign.java:108)
	at s.Sign.sign(Sign.java:454)
	at s.Sign.main(Sign.java:532)
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more

[ERROR] Signing Failed

**Comment by KumarVickey** [comment]
It's simple ! Just install Java 8 on your system and try again. It will work... Best of luck ! 👍

**Comment by karma9874** [comment]
You are using JDK 11 you need to use 8, or if it is installed correctly then I guess you need to set up the JAVA_HOME path to it

**Comment by saurabhsharma786** [comment]
karma9874 please tell me how to s3t up the JAVA_HOME path

**Comment by saurabhsharma786** [comment]
ok I found the solution no need to signed with 3rd party source just use this cmd
after installing java 8
sudo update-alternatives --config java
choose java 8 according to number
that's it
