### ISSUE TITLE
Thread object has no attribute 'isAlive'?

### ISSUE THREAD

**Issue by KursatAktunc** [karma9874/AndroRAT#86]
Traceback (most recent call last):
  File "C:\Users\wazz\AndroRAT\androRAT.py", line 55, in <module>
    get_shell(args.ip,args.port)
  File "C:\Users\wazz\AndroRAT\utils.py", line 310, in get_shell
    while t.isAlive(): animate("Waiting for Connections  ")
AttributeError: 'Thread' object has no attribute 'isAlive'

**Comment by rahultalekar** [comment]
@KursatAktunc change t.isAlive()  to t.is_alive() in utils.py on line 310, 375 and 384
