### ISSUE TITLE
getSimDetails not working

### ISSUE THREAD

**Issue by justekoro** [karma9874/AndroRAT#91]
infos about my phone:
```--------------------------------------------
Manufacturer: Xiaomi
Version/Release: 10
Product: ginkgo
Model: Redmi Note 8
Brand: xiaomi
Device: ginkgo
Host: -----------------
--------------------------------------------
```

issue: when I type "getSimDetails", the program doesnt do anything. I granted all the permissions on my phone.
screenshot:
![image](https://user-images.githubusercontent.com/35098503/127004211-2bcd3c0c-7444-42f2-bce8-f70f45cf25aa.png)

thanks in advance for your answer!

**Comment by Subass21** [comment]
when I try to install i get this error and I cant clear it :

Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at s.Sign.addDigestsToManifest(Sign.java:108)
	at s.Sign.sign(Sign.java:454)
	at s.Sign.main(Sign.java:532)
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more

**Comment by justekoro** [comment]
hi, any news?

**Comment by justekoro** [comment]
bumping
