### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by isl4nd** [karma9874/AndroRAT#95]
└─$ python3 androRAT.py --build -i 192.169.5.55 -p 8000 -o evil.apk
Traceback (most recent call last):
  File "/home/kali/AndroRAT/androRAT.py", line 1, in <module>
    from utils import *
  File "/home/kali/AndroRAT/utils.py", line 12, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

**Comment by JigolKa** [comment]
Hey,
You need to install the library 'pyngrok'
$ pip install pyngrok
